import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Providers from "@/app/components/auth/providers";
import NavBar from "./components/utility/navabr";
import Footer from "./components/utility/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Providers>
        <body className={inter.className}>
          <NavBar />
          <div className="min-h-screen bg-red-200">
            {children}
          </div>
        </body>
        <Footer/>
      </Providers>
    </html>
  );
}
